### ISSUE TITLE
Breaks with Karma 0.13

### ISSUE THREAD

**Issue by mindmelting** [wilsonjackson/karma-angular-filesort#1]
https://github.com/karma-runner/karma/issues/851#issuecomment-115869061

**Comment by wilsonjackson** [comment]
@mindmelting Thanks for the heads up. I don't have a lot of time to spend looking for a workaround ATM, but I'll keep this on my radar.

**Comment by mindmelting** [comment]
No worries, your package is used by a popular angular generator (generator-gulp-angular), which would probably restrict them from upgrading Karma too...

I'll take a look over the next couple of days too.

**Comment by mprokopowicz** [comment]
+1

**Comment by marshall007** [comment]
I just ran into this as well. Was able to get it working and submitted a PR.

**Comment by gruppjo** [comment]
Hi, any news on this? It's keeping our generator from upgrading to karma 0.13 as well. Please let me know if I can help

**Comment by wilsonjackson** [comment]
Sorry for the delay, I've just published a compatible version thanks to @marshall007's PR. You'll need to use 1.0.0 with Karma 0.13.

**Comment by gruppjo** [comment]
wonderful. work's like a charm. Thank you!
